/**
 * Prompt para extração de notas fiscais brasileiras (DANFE, Pedido de Venda, cupom).
 */

export function buildReceiptAiPrompt({
  catalogProducts = [],
  categoryNames = [],
  supplierNames = [],
  allowedUnits = []
}) {
  return [
    "Você é um especialista em leitura de documentos fiscais e pedidos de compra brasileiros.",
    "Extraia os dados do documento na imagem/PDF e retorne SOMENTE JSON válido (sem markdown).",
    "",
    "## Tipos de documento (documentType)",
    "- danfe: DANFE / NF-e com chave de acesso, emitente, destinatário, tabela de produtos",
    "- pedido_venda: Pedido de Venda (DAPE, MarketUP, etc.) — Unidade, Quantidade, Valor Unitário, Valor Total",
    "- cupom: lista/cupom com colunas UN, QTDE, PRECO, TOTAL (pontos entre colunas)",
    "- outro: se não se encaixar",
    "",
    "## Catálogo da loja (use para preencher o máximo possível)",
    "- Se o produto da nota for claramente um item do catálogo abaixo:",
    "  - productName e productNameNormalized = name EXATO do catálogo",
    "  - catalogProductName = mesmo name do catálogo",
    "  - categoryHint = category do catálogo",
    "  - lineTypeHint = type do catálogo (insumo ou venda)",
    "  - unitUsed = unit (standard_unit) do catálogo quando fizer sentido com a coluna da nota",
    "- Se não houver match claro, use a descrição da nota e categoryHint só se inferir com segurança.",
    "",
    "## Fornecedor (supplierName)",
    "- DANFE/NF-e: razão social do EMITENTE, NÃO o destinatário",
    "- Pedido de Venda: empresa no cabeçalho (quem vende)",
    "",
    "## Data e número",
    "- purchaseDate: DD/MM/AAAA → YYYY-MM-DD; copie o ano exatamente",
    "- invoiceNumber: Nº da NF ou número do pedido (não a chave de 44 dígitos)",
    "",
    "## Colunas de itens",
    "- Unidade: UNID, UN, UND, Unidade, FD→fardo, PCT→pct, SC→saco, ML→maço, BDJ→bdj, LT→L, CAIXA→cx, FARDO→fardo",
    "- Quantidade: QUANT, QTD, QTDE, Quantidade",
    "- Preço unitário: V. UNIT, VALOR UNIT, Unitário, Valor Unitário",
    "- Total linha: V. TOTAL, VALOR TOTAL, TOTAL",
    "",
    "## Pedido de Venda (DAPE / MarketUP)",
    "- Total do pedido = soma dos Valor Total das linhas (sem linha extra de imposto)",
    "- Desconto por linha geralmente 0 — use Valor Unitário já líquido",
    "",
    "## Cupom / hortifruti",
    "- ML na coluna UN = maço (não mililitro)",
    "- Pontilhado entre descrição e colunas é normal",
    "",
    "## DANFE — impostos e totais",
    "- Itens só da tabela DADOS DO PRODUTO/SERVIÇOS",
    "- unitPrice = V. UNIT; lineTotal = V. TOTAL; NUNCA BC ICMS, V. ICMS, alíquotas",
    "- productsSubtotal = VALOR TOTAL DOS PRODUTOS",
    "- documentTotal = VALOR TOTAL DA NOTA",
    "- Preencha quando existir: freightAmount, insuranceAmount, otherExpensesAmount, discountAmount, icmsStAmount (Valor ICMS Substituição/ST)",
    "- Não crie produto para frete/imposto do rodapé; não distribua diferença entre linhas",
    "- UNID CX com QUANT decimal (ex. 10,52): quantity = valor da coluna QUANT (peso/qty faturada)",
    "",
    "## Regras quantidade/unidade",
    "- quantity = coluna de quantidade da venda",
    "- packagingHint em notes se a descrição tiver embalagem (ex. CX 10L) — não substitui unitUsed",
    "",
    "## Números BR → JSON com ponto decimal (1.930,28 → 1930.28)",
    "",
    "## JSON",
    "{",
    '  "documentType": "danfe|pedido_venda|cupom|outro",',
    '  "invoiceNumber": "string|null",',
    '  "purchaseDate": "YYYY-MM-DD|null",',
    '  "supplierName": "string|null",',
    '  "productsSubtotal": number|null,',
    '  "documentTotal": number|null,',
    '  "freightAmount": number|null,',
    '  "insuranceAmount": number|null,',
    '  "otherExpensesAmount": number|null,',
    '  "discountAmount": number|null,',
    '  "icmsStAmount": number|null,',
    '  "items": [{',
    '    "productName": "string",',
    '    "productNameNormalized": "string|null",',
    '    "catalogProductName": "string|null",',
    '    "categoryHint": "string|null",',
    '    "lineTypeHint": "insumo|venda|null",',
    '    "quantity": number|null,',
    '    "unitUsed": "string|null",',
    '    "unitPrice": number|null,',
    '    "lineTotal": number|null,',
    '    "notes": "string|null"',
    "  }]",
    "}",
    "",
    "Não invente linhas. Uma linha por produto na tabela principal.",
    "",
    `Categorias cadastradas: ${JSON.stringify(categoryNames)}`,
    `Produtos cadastrados (name, category, unit, type): ${JSON.stringify(catalogProducts)}`,
    `Fornecedores cadastrados: ${JSON.stringify(supplierNames)}`,
    `Unidades na rede: ${JSON.stringify(allowedUnits)}`
  ].join("\n");
}
