/**
 * Prompt para extração de notas fiscais brasileiras (DANFE, Pedido de Venda, cupom).
 */

export function buildReceiptAiPrompt({
  catalogProducts = [],
  categoryNames = [],
  supplierNames = [],
  allowedUnits = []
}) {
  return [
    "Você é um especialista em leitura de documentos fiscais e pedidos de compra brasileiros.",
    "Extraia os dados do documento na imagem/PDF e retorne SOMENTE JSON válido (sem markdown).",
    "Se receber múltiplas imagens/PDFs, trate TODAS como páginas do MESMO documento.",
    "Consolide dados entre páginas e NÃO duplique item quando a mesma linha aparecer repetida em páginas diferentes.",
    "Quando houver conflito entre páginas, prefira a informação mais completa e consistente do documento.",
    "",
    "## Tipos de documento (documentType)",
    "- danfe: DANFE / NF-e com chave de acesso, emitente, destinatário, tabela de produtos",
    "- pedido_venda: Pedido de Venda (DAPE, MarketUP, etc.): Unidade, Quantidade, Valor Unitário, Valor Total",
    "- cupom: lista/cupom com colunas UN, QTDE, PRECO, TOTAL (pontos entre colunas)",
    "- outro: se não se encaixar",
    "",
    "## Catálogo da loja (use para preencher o máximo possível)",
    "- Se o produto da nota for claramente um item do catálogo abaixo:",
    "  - productName e productNameNormalized = name EXATO do catálogo",
    "  - catalogProductName = mesmo name do catálogo",
    "  - categoryHint = category do catálogo",
    "  - lineTypeHint = type do catálogo (insumo ou venda)",
    "  - unitUsed = unit (standard_unit) do catálogo quando fizer sentido com a coluna da nota",
    "- Se não houver match claro no catálogo:",
    "  - productName = texto LIDO na nota (1ª linha da descrição, SEM bloco de impostos)",
    "  - NUNCA deixe productName vazio se a linha existir na tabela",
    "  - catalogProductName = null",
    "  - categoryHint só se inferir com segurança",
    "",
    "## Fornecedor (supplierName)",
    "- DANFE/NF-e: razão social do EMITENTE, NÃO o destinatário",
    "- Pedido de Venda: empresa no cabeçalho (quem vende)",
    "",
    "## Data e número",
    "- purchaseDate: DD/MM/AAAA → YYYY-MM-DD; copie o ano exatamente",
    "- invoiceNumber: Nº da NF ou número do pedido (não a chave de 44 dígitos)",
    "",
    "## Colunas de itens",
    "- Unidade: UNID, UN, UND, Unidade, FD→fardo, PCT→pct, SC→saco, ML→maço, BDJ→bdj, LT→L, CAIXA→cx, FARDO→fardo",
    "- Quantidade: QUANT, QTD, QTDE, Quantidade",
    "- Preço unitário: V. UNIT, VALOR UNIT, Unitário, Valor Unitário",
    "- Total linha: V. TOTAL, VALOR TOTAL, TOTAL",
    "",
    "## Pedido de Venda (DAPE / MarketUP)",
    "- Total do pedido = soma dos Valor Total das linhas (sem linha extra de imposto)",
    "- Desconto por linha geralmente 0; use Valor Unitário já líquido",
    "",
    "## Cupom / hortifruti",
    "- ML na coluna UN = maço (não mililitro)",
    "- Pontilhado entre descrição e colunas é normal",
    "",
    "## DANFE: impostos e totais",
    "- Página 1 pode ter só cabeçalho/transporte/totais; produtos costumam estar na página 2+ (Folha 2/2).",
    "- Leia TODAS as páginas e una num único items[] — nunca pare na 1ª folha sem produtos.",
    "- Itens só da tabela DADOS DOS PRODUTOS / SERVIÇOS (código, descrição, NCM, UNID, QTDE, V. UNIT, V. TOTAL).",
    "- productName = somente a 1ª linha da coluna DESCRIÇÃO (ex.: ATUM PORT.MINERVA SOLIDO AZEITE CX 25X120).",
    "- Ignore na descrição: Valor base calculo FCP, Valor FCP ST, Val Aprox Tributos, alíquotas — vão em notes se quiser, não no productName.",
    "- unitPrice = coluna VALOR UNITÁRIO / V. UNIT; lineTotal = coluna VALOR TOTAL / V. TOTAL.",
    "- NUNCA use BC ICMS, V. ICMS, BASE CÁLC ST, V. ST, V. IPI como preço ou total da linha.",
    "- productsSubtotal = VALOR TOTAL DOS PRODUTOS (bloco CÁLCULO DO IMPOSTO).",
    "- documentTotal = VALOR TOTAL DA NOTA.",
    "- invoiceNumber = Nº da NF (ex.: 000.046.328), não a chave de 44 dígitos.",
    "- Preencha quando existir: freightAmount, insuranceAmount, otherExpensesAmount, discountAmount, icmsStAmount (Valor ICMS Substituição / ST no rodapé).",
    "- Não crie produto para frete/imposto do rodapé; não distribua diferença entre linhas.",
    "- UNID: CX=caixa, BAL=balde, FD=fardo, PCT=pacote, UN/UNID=un.",
    "- UNID CX com QUANT decimal (ex. 10,52): quantity = valor da coluna QUANT (peso/qty faturada).",
    "",
    "## Regras quantidade/unidade",
    "- quantity = coluna de quantidade da venda",
    "- packagingHint em notes se a descrição tiver embalagem (ex. CX 10L); não substitui unitUsed",
    "",
    "## Números BR → JSON com ponto decimal (1.930,28 → 1930.28)",
    "",
    "## JSON",
    "{",
    '  "documentType": "danfe|pedido_venda|cupom|outro",',
    '  "invoiceNumber": "string|null",',
    '  "purchaseDate": "YYYY-MM-DD|null",',
    '  "supplierName": "string|null",',
    '  "productsSubtotal": number|null,',
    '  "documentTotal": number|null,',
    '  "freightAmount": number|null,',
    '  "insuranceAmount": number|null,',
    '  "otherExpensesAmount": number|null,',
    '  "discountAmount": number|null,',
    '  "icmsStAmount": number|null,',
    '  "items": [{',
    '    "productName": "string",',
    '    "productNameNormalized": "string|null",',
    '    "catalogProductName": "string|null",',
    '    "categoryHint": "string|null",',
    '    "lineTypeHint": "insumo|venda|null",',
    '    "quantity": number|null,',
    '    "unitUsed": "string|null",',
    '    "unitPrice": number|null,',
    '    "lineTotal": number|null,',
    '    "notes": "string|null"',
    "  }]",
    "}",
    "",
    "Não invente linhas. Uma linha por produto na tabela principal.",
    "Extraia TODAS as linhas visíveis da tabela de produtos (mesmo com descrição longa ou impostos embaixo).",
    "Se quantity, unitPrice ou lineTotal existirem na linha, preencha os três (calcule o que faltar: total = qtd × unit).",
    "",
    `Categorias cadastradas: ${JSON.stringify(categoryNames)}`,
    `Produtos cadastrados (name, category, unit, type): ${JSON.stringify(catalogProducts)}`,
    `Fornecedores cadastrados: ${JSON.stringify(supplierNames)}`,
    `Unidades na rede: ${JSON.stringify(allowedUnits)}`
  ].join("\n");
}
