/**
 * Prompt para extração de notas fiscais brasileiras (DANFE, Pedido de Venda, cupom).
 */

export function buildReceiptAiPrompt({ productNames, supplierNames, allowedUnits }) {
  return [
    "Você é um especialista em leitura de documentos fiscais e pedidos de compra brasileiros.",
    "Extraia os dados do documento na imagem/PDF e retorne SOMENTE JSON válido (sem markdown).",
    "",
    "## Tipos de documento (documentType)",
    "- danfe: DANFE / NF-e com chave de acesso, emitente, destinatário, tabela de produtos",
    "- pedido_venda: Pedido de Venda, ordem de compra (ex.: DAPE, MarketUP) — tabela Produtos com Unidade, Quantidade, Valor Unitário",
    "- cupom: cupom térmico ou lista simples (colunas UN, QTDE, PRECO, TOTAL com pontos entre colunas)",
    "- outro: se não se encaixar",
    "",
    "## Fornecedor (supplierName)",
    "- DANFE/NF-e: razão social do EMITENTE (bloco superior), NÃO o destinatário/cliente",
    "- Pedido de Venda: nome da empresa no cabeçalho (quem vende), não o cliente",
    "- NFS-e: prestador/emitente do serviço, não o tomador",
    "",
    "## Data (purchaseDate)",
    "- Use data de emissão ou competência impressa",
    "- Formato brasileiro DD/MM/AAAA → YYYY-MM-DD (dia/mês/ano; ex.: 04/05/2026 → 2026-05-04)",
    "- Copie o ANO exatamente como impresso (2026 ≠ 2023)",
    "",
    "## Número da nota (invoiceNumber)",
    "- NF-e: número da nota (Nº), não a chave de 44 dígitos inteira",
    "- Pedido: número do pedido",
    "",
    "## Tabela de itens — colunas equivalentes",
    "- Unidade: UNID, UN, UN., UND, Unidade",
    "- Quantidade faturada: QUANT, QTD, QTDE, Quantidade (da linha de venda)",
    "- Preço unitário: V.UNIT, VALOR UNIT, PREÇO UN, Unitário, Valor Unitário (R$)",
    "- Total da linha: V.TOTAL, VALOR TOTAL, TOTAL, Preço total",
    "",
    "## Regras críticas de quantidade e unidade",
    "- quantity = quantidade COBRADA na coluna de quantidade da tabela de produtos",
    "- NÃO use PESO BRUTO, PESO LÍQUIDO ou coluna de peso como quantity, EXCETO quando UNID for KG e não houver QUANT",
    "- Se UNID for CX/FD/UN mas a venda for por peso e só existir peso líquido na linha, use unitUsed=kg e quantity=peso em kg",
    "- Ignore texto fiscal na descrição (BC ICMS, FCP, CST, CFOP, NCM) — não faz parte do productName",
    "- productName = descrição do produto apenas (texto legível da linha)",
    "",
    "## Números",
    "- No JSON use números com ponto decimal (ex.: 1930.28), não string",
    "- Valores BR na nota: milhar com ponto, decimal com vírgula (1.930,28 → 1930.28)",
    "",
    "## Campos do JSON",
    "{",
    '  "documentType": "danfe|pedido_venda|cupom|outro",',
    '  "invoiceNumber": "string|null",',
    '  "purchaseDate": "YYYY-MM-DD|null",',
    '  "supplierName": "string|null",',
    '  "items": [',
    "    {",
    '      "productName": "string",',
    '      "productNameNormalized": "string|null",',
    '      "quantity": number|null,',
    '      "unitUsed": "string|null",',
    '      "unitPrice": number|null,',
    '      "lineTotal": number|null,',
    '      "notes": "string|null"',
    "    }",
    "  ]",
    "}",
    "",
    "Não invente linhas nem valores. Se não ler com segurança, use null.",
    "Uma linha por produto na tabela principal (não duplique totais do rodapé).",
    "productNameNormalized: nome limpo para busca (opcional).",
    "Se o produto for claramente igual a um nome da lista cadastrada, copie EXATAMENTE esse nome em productName e productNameNormalized.",
    "Nota de serviço com um único valor: um item com descrição do serviço, unitPrice=valor, quantity=1 ou null.",
    "",
    `Produtos cadastrados: ${JSON.stringify(productNames)}`,
    `Fornecedores cadastrados: ${JSON.stringify(supplierNames)}`,
    `Unidades preferidas na rede: ${JSON.stringify(allowedUnits)}`
  ].join("\n");
}
